### ISSUE TITLE
Error when compile?

### ISSUE THREAD

**Issue by mike1985dev** [nt4f04uNd/genius_api_unofficial#2] opened 2021-07-20 16:22 UTC
Hi, when I compile my app it comes a error.
The plugin use 0.12.0 version of http package and I need 0.13.0
Can you change it?
Thx very much!

**Comment by nt4f04uNd** [comment] 2021-07-20 18:56
It should be resolved with 2.0.0

**Closed as completed by nt4f04uNd** 2021-07-20 18:56 UTC

**Comment by mike1985dev** [comment] 2021-07-21 18:00
There is still a issue. A incompatiblety with the in_app_purchase package in my App.

**Comment by nt4f04uNd** [comment] 2021-07-21 18:10
Elaborate on what the issue is and how in_app_purchase is related

**Comment by mike1985dev** [comment] 2021-07-21 18:26
When I want to download the plugin comes:
My app depends on both flutter any from sdk and in_app_purchase 1.0.6 , flutter_test is incompatible with genius app unofficial.

**Comment by nt4f04uNd** [comment] 2021-07-21 19:14
I cannot reproduce

> My app depends on both flutter any from sdk and in_app_purchase 1.0.6 , flutter_test is incompatible with genius app unofficial.

This doesn't really tell me anything. Either provide a full error log, or a reproducible sample (better both)

**Comment by nt4f04uNd** [comment] 2021-07-21 19:30
Actually, a full error log will be sufficient

**Comment by mike1985dev** [comment] 2021-07-22 17:51
when I download the plugin comes the following message:

Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and every version of in_app_purchase_ios depends on test ^1.16.0, every version of in_app_purchase_ios requires test_api 0.2.19 or test ^1.16.6.
And because every version of flutter_test from sdk depends on test_api 0.3.0 and test >=1.16.6 depends on shelf_static ^1.0.0, if flutter_test any from sdk and in_app_purchase_ios any then shelf_static ^1.0.0.
And because shelf_static >=1.0.0 depends on http_parser ^4.0.0 and http >=0.11.3+17 <0.13.0-nullsafety.0 depends on http_parser >=0.0.1 <4.0.0, one of flutter_test any from sdk or in_app_purchase_ios any or http >=0.11.3+17 <0.13.0-nullsafety.0 must be false.
And because genius_api_unofficial <2.0.0 depends on http ^0.12.0+4 and genius_api_unofficial >=2.0.0 depends on meta ^1.7.0, if flutter_test any from sdk and in_app_purchase_ios any and genius_api_unofficial any then meta ^1.7.0.
And because every version of flutter from sdk depends on meta 1.3.0 and in_app_purchase >=0.6.0 depends on in_app_purchase_ios ^0.1.0, one of flutter_test any from sdk or genius_api_unofficial any or flutter any from sdk or in_app_purchase >=0.6.0 must be false.
And because blackmonkey depends on both flutter any from sdk and in_app_purchase ^1.0.6, flutter_test from sdk is incompatible with genius_api_unofficial.
So, because blackmonkey depends on both genius_api_unofficial any and flutter_test any from sdk, version solving failed.
pub finished with exit code 65

**Comment by nt4f04uNd** [comment] 2021-07-22 18:35
Can you also provide me with the `flutter doctor -v` output? I wonder how much your flutter version is old

**Comment by mike1985dev** [comment] 2021-07-22 18:40
I Updated my dart and flutter version and it comes the same error

**Comment by nt4f04uNd** [comment] 2021-07-22 18:57
I already filed an issue to flutter repository, because `test` shouldn't be in `dependencies` of `in_app_purchase_ios`

For now you should be able to just do this

```yaml
dependency_overrides:
   meta: ^1.3.0
```

I'm not interested in downgrading the meta package back, as this is not really an issue of the package

**Comment by nt4f04uNd** [comment] 2021-07-22 19:07
> I'm not interested in downgrading the meta package back, as this is not really an issue of the package

Ah, actually why not, this doesn't seem to affect anything. Please try the overrides thing above to see if it helps, and if yes, I will change it back to 1.3.0

**Comment by mike1985dev** [comment] 2021-07-22 19:30
I want to upgrade my meta 1.3.0 to latest 1.7.0, but it's not possible? Flutter and dart are up to date.

**Comment by nt4f04uNd** [comment] 2021-07-22 20:10
I'm not really sure about that

**Comment by mike1985dev** [comment] 2021-07-23 17:34
Can you go back to meta 1.3.0 ?

**Comment by nt4f04uNd** [comment] 2021-07-23 17:40
> Please try the overrides thing above to see if it helps, and if yes, I will change it back to 1.3.0

**Comment by mike1985dev** [comment] 2021-07-23 20:53
I tried everything, but nothing's helped.

**Comment by mike1985dev** [comment] 2021-07-27 17:52
I load the lyrics manually in my App. But how I parse the lyrics from the lyrics URL?

**Comment by nt4f04uNd** [comment] 2021-08-02 14:15
If you are asking whether there's an API for pulling off the song lyrics, no there isn't
